<?php
	// Game ----------------------------- Game
	//$game = 1; // Georgia Fantasy 5
	#$game = 2; // Mega Millions
	//$game = 3; // Georgia Lotto South
	$game = 4; // Florida Fantasy 5
	//$game = 5; // Florida Mega Money
	#$game = 6; // Florida Lotto
	#$game = 7; // Powerball
	// Game ----------------------------- Game

	require ("includes/games_switch.incl");

	require ("includes/mysqli.php");

	//start HTML page
	echo "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">
		<html xmlns=\"http://www.w3.org/1999/xhtml\">";
	echo "<head>\n";
	echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n";
	echo "<title>Lottery Landing Page</title>\n";
	echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"view.css\" media=\"all\">\n";
	echo "<script type=\"text/javascript\" src=\"view.js\"></script>\n";
	echo "</head>\n";

	
	echo "<body id=\"main_body\" >\n";
	echo "	\n";
	echo "	<img id=\"top\" src=\"top.png\" alt=\"\">\n";
	echo "	<div id=\"form_container\">\n";
	echo "	\n";
	echo "		<h1><a>Lottery Landing Page</a></h1>\n";
	echo "		<form id=\"form_14026\" class=\"appnitro\"  method=\"post\" action=\"\">\n";
	echo "					<div class=\"form_description\">\n";
	echo "			<h2>Lottery Landing Page</h2>\n";
	echo "			<p>Select a lottery game!</p>\n";
	echo "		</div>						\n";
	echo "			<ul >\n";
	echo "			\n";
	echo "					<li id=\"li_1\" >\n";
	echo "		<label class=\"description\" for=\"element_1\">Game </label>\n";
	echo "		<div>\n";
	echo "		<select class=\"element select medium\" id=\"element_1\" name=\"element_1\"> \n";
	echo "			<option value=\"\" selected=\"selected\"></option>\n";
	echo "			<option value=\"1\" >Florida Fantasy 5</option>\n";
	echo "			<option value=\"2\" >Florida Lotto</option>\n";
	echo "			<option value=\"3\" >Third option</option>\n";
	echo "		</select>\n";
	echo "		</div> \n";
	echo "		</li>		<li id=\"li_2\" >\n";
	echo "		<label class=\"description\" for=\"element_2\">Function </label>\n";
	
	echo "		<div>\n";
	echo "		<select class=\"element select medium\" id=\"element_2\" name=\"element_2\"> \n";
	echo "			<option value=\"\" selected=\"selected\"></option>\n";
	echo "			<option value=\"1\" >Display</option>\n";
	echo "			<option value=\"2\" >Analyze</option>\n";
	echo "			<option value=\"3\" >Test</option>\n";
	echo "		</select>\n";
	echo "		</div> \n";
	echo "		</li>		<li id=\"li_3\" >\n";
	/*
	echo "		<label class=\"description\" for=\"element_3\">Drop Down </label>\n";
	
	
	echo "		<div>\n";
	echo "		<select class=\"element select medium\" id=\"element_3\" name=\"element_3\"> \n";
	echo "			<option value=\"\" selected=\"selected\"></option>\n";
	echo "			<option value=\"1\" >First option</option>\n";
	echo "			<option value=\"2\" >Second option</option>\n";
	echo "			<option value=\"3\" >Third option</option>\n";
	echo "		</select>\n";
	echo "		</div> \n";
	*/
	echo "		</li>\n";
	echo "			\n";
	echo "					<li class=\"buttons\">\n";
	echo "			    <input type=\"hidden\" name=\"form_id\" value=\"14026\" />\n";
	echo "			    \n";
	echo "				<input id=\"saveForm\" class=\"button_text\" type=\"submit\" name=\"submit\" value=\"Submit\" />\n";
	echo "		</li>\n";
	echo "			</ul>\n";
	echo "		</form>	\n";
	echo "		<div id=\"footer\">\n";
	echo "			Generated by <a href=\"http://www.phpform.org\">pForm</a>\n";
	echo "		</div>\n";
	echo "	</div>\n";
	echo "	<img id=\"bottom\" src=\"bottom.png\" alt=\"\">\n";
	echo "	</body>\n";

	
	/*
	echo "<form name=\"check_form\" method=\"post\" action=\"fl_mm_check_numbers.php\">\n";

	echo "<table width=\"80%\" border=\"0\">";
	echo "<tr> ";
	echo "<td width=\"35%\">"; 
        echo "<div align=\"right\"><font face=\"Arial, Helvetica, sans-serif\"><b>Draw Date:</b></font></div>";
	echo "</td>";
	echo "<td width=\"65%\">"; 
	echo "<select name=\"date\">";

	// get everything from catalog table
	$query = "SELECT date FROM fl_mm_draws ";
	$query .= "ORDER BY date DESC ";
	$mysqli_result = mysqli_query($query, $mysqli_link_florida) or die (mysqli_error();

	// get each row
	while($row = mysqli_fetch_row($mysqli_result))
	{
		echo "<option value=\"$row[0]\">$row[0]</option>";
	}
        
	echo "</select>";
	echo "</td>";
	echo "</tr>";
	echo "<tr>"; 
	echo "<td width=\"35%\">"; 
        echo "<div align=\"right\"><font face=\"Arial, Helvetica, sans-serif\"><b>Picks:</b></font></div>";
	echo "</td>";
	echo "<td width=\"65%\">"; 
    echo "<select name=\"pick\">";

	$mysqli_result = mysqli_list_tables("florida";

	// get each row
	while($row = mysqli_fetch_row($mysqli_result))
	{
		if (preg_match ("/fl_picks_mm_/i", "$row[0]")) {
			echo "<option value=\"$row[0]\">$row[0]</option>";
		} 
	}
        
	echo "</select>";
	echo "</td>";
	echo "</tr>";
	echo "<tr>"; 
	echo "<td width=\"35%\">"; 
        echo "<div align=\"right\"><b><font face=\"Arial, Helvetica, sans-serif\"></font></b></div>";
	echo "</td>";
	echo "<td width=\"65%\">&nbsp;</td>";
	echo "</tr>";
	echo "<tr>"; 
	echo "<td width=\"35%\">"; 
        echo "<div align=\"right\"><font face=\"Arial, Helvetica, sans-serif\"><b>Payout</b></font></div>";
	echo "</td>";
	echo "<td width=\"65%\">&nbsp;</td>";
	echo "</tr>";
	echo "</tr>";
	echo "<tr>"; 
	echo "<td width=\"35%\">"; 
        echo "<div align=\"right\"><b><font face=\"Arial, Helvetica, sans-serif\">Number of past draws:</font></b></div>";
	echo "</td>";
	echo "<td width=\"65%\">"; 
        echo "<select name=\"draws\">";
		echo "<option value=\"1\">1</option>";
		echo "<option value=\"5\">5</option>";
		echo "<option value=\"10\">10</option>";
		echo "<option value=\"15\">15</option>";
		echo "<option value=\"20\">20</option>";
		echo "<option value=\"30\">30</option>";
		echo "<option value=\"50\">50</option>";
		echo "<option value=\"100\">100</option>";
		echo "</select>";
	echo "</td>";
	echo "</tr>";
	echo "<tr>"; 
	echo "<td width=\"35%\">"; 
        echo "<div align=\"right\"><b><font face=\"Arial, Helvetica, sans-serif\">4+PB:</font></b></div>";
	echo "</td>";
	echo "<td width=\"65%\">"; 
        echo "<input type=\"text\" name=\"five_pb\" size=\"6\">";
	echo "</td>";
	echo "</tr>";
	echo "<tr>";
	echo "<td width=\"35%\">&nbsp;</td>";
	echo "<td width=\"65%\">&nbsp;</td>";
	echo "</tr>";
	echo "<tr>";
	echo "<td width=\"35%\">&nbsp;</td>";
	echo "<td width=\"65%\">"; 
        echo "<input type=\"submit\" name=\"Submit\" value=\"Check Numbers\">";
	echo "</td>";
	echo "</tr>";
	echo "</table>";
	echo "<p>&nbsp;</p>";
	echo "</form>";
	*/

?>
